spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  servlet:
    context-path: /sefer
sefer:
  store: "ваша директория"
  to-zip: "pdf,doc,docx,rtf,txt,xls,xlsx,xlsb,xlsm,csv,ppt,pptx,vsd,vsdx,mpp"
